<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var \Crimson\AdvancedTableView\ViewModel\ProductColumns $visibleColumns
 */
?>
<?php
$visibleColumns = $block->getColumnsViewModel();
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } elseif ($block->getMode() == 'table') {
        $viewMode = 'table';
        $imageDisplayArea = 'catalog_table_view';
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }else{
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <?php if ($viewMode != 'table'): ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <li class="item product product-item">
                <div class="product-item-info"
                     id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                     data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = 'left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>

                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">
                                    <?php if ($_product->isSaleable()):?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                              action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                              method="post">
                                            <?php $options = $block->getData('viewModel')->getOptionsData($_product); ?>
                                            <?php foreach ($options as $optionItem): ?>
                                                <input type="hidden"
                                                       name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                                                       value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                            <?php endforeach; ?>
                                            <input type="hidden"
                                                   name="product"
                                                   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden"
                                                   name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                   value="<?=
                                                   /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                    ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                    class="action tocart primary"
                                                    disabled>
                                                <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        </form>
                                    <?php else:?>
                                        <?php if ($_product->isAvailable()):?>
                                            <div class="stock available">
                                                <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else:?>
                                            <div class="stock unavailable">
                                                <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <?= ($pos && strpos($pos, $viewMode . '-primary')) ?
                                    /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                        $position,
                                        'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                    ) : '' ?>
                                <div data-role="add-to-links" class="actions-secondary">
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                                <?= ($pos && strpos($pos, $viewMode . '-secondary')) ?
                                    /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                        $position,
                                        'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                    ) : '' ?>
                            </div>
                            <?php if ($showDescription): ?>
                                <div class="product description product-item-description">
                                    <?= /* @noEscape */ $_helper->productAttribute(
                                        $_product,
                                        $_product->getShortDescription(),
                                        'short_description'
                                    ) ?>
                                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                       title="<?= /* @noEscape */ $_productNameStripped ?>"
                                       class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?= ($pos && strpos($pos, $viewMode . '-actions')) ?
                /* @noEscape */ $secureRenderer->renderStyleAsTag(
                    $position,
                    'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                ) : '' ?>
            </li>
            <?php endforeach; ?>
        </ol>
        <?php else: ?>
        <div class="table-wrapper">
            <table class="products list items">
                <?php if ($visibleColumns->isMassSelectVisible()):?>
                    <div class="tocart-toolbar-select">
                        <button type="button" data-role="all-tocart" title="<?= $block->escapeHtmlAttr(__('Add All to Cart')) ?>" class="action tocart">
                            <span><?= $block->escapeHtml(__('Add All to Cart')) ?></span>
                        </button>
                        <input type="checkbox" name="" id="tocart-select-all" data-role="select-all" />
                        <label class="label" for="tocart-select-all"><?= $escaper->escapeHtml(__('Select all')) ?></label>
                    </div>
                <?php endif; ?>
                <caption class="table-caption"><?= $escaper->escapeHtml(__('Table product view')) ?></caption>
                <thead>
                    <tr>
                        <?php if ($visibleColumns->isMassSelectVisible()):?>
                            <th scope="col" class="col checkbox"><span><?= $escaper->escapeHtml(__('')) ?></span></th>
                        <?php endif; ?>
                        <?php if ($visibleColumns->isImageVisible()):?>
                            <th scope="col" class="col image"><span><?= $escaper->escapeHtml(__('Image')) ?></span></th>
                        <?php endif; ?>
                        <?php if ($visibleColumns->isNameVisible()):?>
                            <th scope="col" colspan="2" class="col name"><span><?= $escaper->escapeHtml(__('Product Name')) ?></span></th>
                        <?php endif; ?>
                        <?php if ($visibleColumns->isSKUVisible()):?>
                            <th scope="col" class="col sku"><span><?= $escaper->escapeHtml(__('SKU')) ?></span></th>
                        <?php endif; ?>
                        <?php if ($visibleColumns->isPriceVisible()):?>
                            <th scope="col" class="col price"><span><?= $escaper->escapeHtml(__('Price')) ?></span></th>
                        <?php endif; ?>
                        <?php if ($visibleColumns->isQtyVisible()):?>
                            <th scope="col" class="col qty"><span><?= $escaper->escapeHtml(__('Qty')) ?></span></th>
                        <?php endif; ?>
                        <?php if ($visibleColumns->isActionsVisible() && $visibleColumns->isActionsSecondaryVisible()):?>
                            <th scope="col" class="col actions"><span><?= $escaper->escapeHtml(__('Actions')) ?></span></th>
                        <?php endif; ?>
                    </tr>
                </thead>
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product): ?>
                <tr class="item product product-item">

                    <?php if ($visibleColumns->isMassSelectVisible()):?>
                        <td class="col col-checkbox">
                            <input type="checkbox"
                                name="selected[<?= /* @noEscape */ $_product->getId()*1 ?>]" data-role="select-product"
                                <?= !$_product->isAvailable() ? 'disabled' : '' ?>
                                class="checkbox product-item-checkbox" />
                        </td>
                    <?php endif; ?>

                    <?php if ($visibleColumns->isImageVisible()):?>
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = 'left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;';
                        }
                        ?>
                        <td class="col col-image">
                            <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                class="product photo product-item-photo"
                                tabindex="-1">
                                <?= $productImage->toHtml() ?>
                            </a>
                        </td>
                    <?php endif; ?>

                    <?php if ($visibleColumns->isNameVisible()):?>
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <td data-th="<?= $escaper->escapeHtml(__('Name')) ?>" colspan="2" class="col col-name">
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                            </a>
                            </strong>
                        </td>
                    <?php endif; ?>

                    <?php if ($visibleColumns->isSKUVisible()):?>
                        <td data-th="<?= $escaper->escapeHtml(__('SKU')) ?>" class="col col-sku">
                            <?= $escaper->escapeHtml($_product->getSku()) ?>
                        </td>
                    <?php endif; ?>

                    <?php if ($visibleColumns->isReviewsVisible()):?>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                    <?php endif; ?>

                    <?php if ($visibleColumns->isPriceVisible()):?>
                        <td data-th="<?= $escaper->escapeHtml(__('Price')) ?>" class="col col-price">
                            <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                        </td>
                    <?php endif; ?>

                    <?php if ($visibleColumns->isQtyVisible()):?>
                        <td data-th="<?= $escaper->escapeHtml(__('Qty')) ?>" 
                            class="col col-qty <?= !$_product->isAvailable() ? 'out-of-stock' : '' ?>">
                            <input type="number"
                                name="qty_column"
                                maxlength="12"
                                value="<?= $escaper->escapeHtmlAttr('0'); ?>"
                                <?= !$_product->isAvailable() ? 'disabled' : '' ?>
                                class="input-text" />
                        </td>
                    <?php endif; ?>

                    <td class="product-item-inner">
                        <div class="product actions product-item-actions">
                            <?php if ($visibleColumns->isActionsVisible()):?>
                            <div class="actions-primary">
                                <?php if ($_product->isSaleable()):?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                    <form data-role="tocart-form"
                                        data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                        action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                        method="post">
                                        <?php $options = $block->getData('viewModel')->getOptionsData($_product); ?>
                                        <?php foreach ($options as $optionItem): ?>
                                            <input type="hidden"
                                                name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                                                value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                        <?php endforeach; ?>
                                        <input type="hidden"
                                            name="product"
                                            value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                        <input type="hidden"
                                            name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                            value="<?=
                                            /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                ?>">
                                        <?= $block->getBlockHtml('formkey') ?>
                                        <input type="number"
                                            name="qty"
                                            id="<?= $escaper->escapeHtmlAttr('id' . $_product->getSku()) ?>"
                                            class="qty" />
                                        <button type="submit"
                                                title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                class="action tocart primary"
                                                disabled>
                                            <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                        </button>
                                    </form>
                                <?php else:?>
                                    <?php if ($_product->isAvailable()):?>
                                        <div class="stock available">
                                            <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                    <?php else:?>
                                        <div class="stock unavailable">
                                            <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                            <?php endif; ?>

                            <?php if ($visibleColumns->isActionsSecondaryVisible()):?>
                                <div data-role="add-to-links" class="actions-secondary">
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>

                        </div>
                        <?php if ($visibleColumns->isDescriptionVisible()):?>
                            <div class="product description product-item-description">
                                <?= /* @noEscape */ $_helper->productAttribute(
                                    $_product,
                                    $_product->getShortDescription(),
                                    'short_description'
                                ) ?>
                                <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                title="<?= /* @noEscape */ $_productNameStripped ?>"
                                class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                            </div>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
        <?php endif; ?>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
                "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
            }
        },
        "[data-role='select-all']": {
            "Crimson_AdvancedTableView/js/select-all-change": {}
        },
        ".col-qty .input-text": {
            "Crimson_AdvancedTableView/js/qty-filler": {
                "checkboxAutoSelect": "true"
            }
        }
    }
    </script>
<?php endif; ?>
